### ISSUE TITLE
scale should install un /usr/local

### ISSUE THREAD

**Issue by estebanlm** [guillep/Scale#10]
Hi, 

I just read the documentation :)
scale should install in `/usr/local` otherwise it will be considered dangerous in some systems and even forbidden in some others (like macOS).
I also suggest to install undefr `/usr/local/scale` (everything there: `/bin`, etc.) and then just create symlinks in `/usr/local/bin`. 

:)

**Comment by guillep** [comment]
I understand this is already the case by the shebangs in the docs:

#! /usr/local/bin/scale
