### ISSUE TITLE
Could not resolve baseline of TaskItShell - installation fails

### ISSUE THREAD

**Issue by psvensson** [guillep/Scale#29]
I've tried all the different ways of installing I've found, but all fails the same way;
-------------------------------------------------
Downloading the latest 80 Image:
    http://files.pharo.org/get-files/80/pharo64.zip
Pharo.image
Downloading the latest pharoVM:
	http://files.pharo.org/get-files/80/pharo64-linux-headless-latest.zip
pharo-vm/pharo
Creating starter scripts pharo and pharo-ui
Loading Scale and Dependencies...
MetacelloNotification: Fetched -> BaselineOfScale-cypress.1 --- filetree:///tmp/scale/cache/../src [:] --- filetree:///tmp/scale/cache/../src
MetacelloNotification: Loaded -> BaselineOfScale-cypress.1 --- filetree:///tmp/scale/cache/../src [:] --- filetree:///tmp/scale/cache/../src
MetacelloNotification: Loading baseline of BaselineOfScale...
MetacelloNotification: ...RETRY->BaselineOfTaskItShell
MetacelloNotification: ...RETRY->BaselineOfTaskItShell
MetacelloNotification: ...FAILED->BaselineOfTaskItShell
Could not resolve: BaselineOfTaskItShell [BaselineOfTaskItShell] in /tmp/scale/cache/pharo-local/package-cache git@github.com:sbragagnolo/taskit.git[master]

...

And later there are problems with copying files, but this is most probably the reason for that.

I'm running a Linux Mint 20; 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux.

Any help appreciated

**Comment by guillep** [comment]
Fixed in #30
